### ISSUE TITLE
Noarch allowing corrupted version of python-future?

### ISSUE THREAD

**Issue by snowman2** [conda-forge/future-feedstock#9]
Issue:

OS: Amaxon Linux

When using the version:
`future-0.16.0-py36_0`

Our builds were working just fine recently. Now, with the noarch release (`future-0.16.0-py_1 `), it seems to be running py_compile on all of the files.

Example:
```
/root/miniconda/envs/testenv/bin/python3.6" -Wi -m py_compile "/root/miniconda/envs/testenv/lib/python3.6/site-packages/libpasteurize/fixes/fix_future_builtins.py"
```

And we are getting this error:
```
 File "/root/miniconda/envs/testenv/lib/python3.6/collections/__init__.py", line 32, in <module>
from reprlib import recursive_repr as _recursive_repr
File "/root/miniconda/envs/testenv/lib/python3.6/site-packages/reprlib/__init__.py", line 7, in <module>
raise ImportError('This package should not be accessible on Python 3. '

ImportError: This package should not be accessible on Python 3. Either you are trying to run from the python-future src folder or your installation of python-future is corrupted.
```

Apologize for not adding conda info as this is from the build logs and I am sharing what I can.

**Comment by tigarmo** [comment]
We also had this issue with the `noarch` version. In our case it affected both `pytest` and `pyinstaller`. Steps that reproduce this: https://gist.github.com/tigarmo/12e900b8b4bb629804ab8b19071a4a44

From my limited understanding the problem has to do with search order for imported packages. From the [docs](https://docs.python.org/3/tutorial/modules.html#the-module-search-path): 

> After initialization, Python programs can modify sys.path. The directory containing the script being run is placed at the beginning of the search path, ahead of the standard library path. This means that scripts in that directory will be loaded instead of modules of the same name in the library directory. This is an error unless the replacement is intended. See section Standard Modules for more information.

So when I run `python /home/jenkins/Work/miniconda/envs/tmp/lib/python3.6/site-packages/pytest.py` and the execution eventually tries to import `reprlib`, it finds the one in the `site-packages` directory added by the `future` package, instead of the one in the standard lib. Note that `python -m pytest` works fine, so for some situations there is a workaround, but pytest itself uses the first form of the call (providing the full path to `pytest.py`), e.g. in its `testdir` fixture. And as I mentioned pytest is just one of the affected packages (the one that broke first here).

I confess that I don't know how to fix this while keeping the package `noarch`. For now we've pinned `future` to the no-noarch version.

cc @nicoddemus @prusse-martin

**Comment by jakirkham** [comment]
Thanks for the info. Sorry for the breakage.

Have pulled the `noarch: python` package (it is labeled `broken`). So updating should pull in the old working one. Also am adding PR ( https://github.com/conda-forge/future-feedstock/pull/10 ) to revert the `noarch: python` change.

**Comment by tigarmo** [comment]
Thanks for the quick fix. I was actually curious if there would be any way to fix this breakage while still keeping the package `noarch`; I understand noarch packages greatly lessen the burdens on conda-forge's servers.

**Comment by jakirkham** [comment]
If you can think of one, would be open to the discussion. That said, as it's build process has protions conditioned on the Python version, I don't think there is another way besides keeping it arch.

**Comment by jakirkham** [comment]
If you have any more issues with this, please let us know and we can revisit.

**Comment by snowman2** [comment]
Thanks!

**Comment by nicoddemus** [comment]
Thanks everybody for working on this. For reference, this package cannot be `noarch` as @jakirkham says because of lines like this:

https://github.com/PythonCharmers/python-future/blob/39a066ed8c29a0b3a32adac2ffd407119fe9ea6d/setup.py#L58
